name: Docker
description: Builds the pre-commit image and optionally push it
author: batinicaz

inputs:
  image_name:
    description: The name of the image being built
    default: ghcr.io/${{ github.repository }}
    required: false
  registry:
    description: The container registry that will be used for image pushing
    default: ghcr.io
    required: false
  push:
    description: Push the image to the container registry?
    default: 'false'
    required: false
  token:
    description: Token to authenticate with registry. Required if pushing
    default: ''
    required: false

runs:
  using: "composite"
  steps:
      - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # ratchet:actions/checkout@v3

      - name: Login to GitHub Container Registry
        if: ${{ inputs.push }}
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # ratchet:docker/login-action@v2
        with:
          registry: ${{ inputs.registry }}
          username: ${{ github.actor }}
          password: ${{ inputs.token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@2eb1c1961a95fc15694676618e422e8ba1d63825 # ratchet:docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: ${{ inputs.push }}
          tags: ${{ inputs.image_name }}:latest